//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW_CL2_JOSUE_CHUPICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int IDE_CLI { get; set; }
        public string NOM_CLI { get; set; }
        public string MOV_CLI { get; set; }
        public int IDE_DIS { get; set; }
        public string COR_CLI { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
    }
}
