//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW_CL2_JOSUE_CHUPICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        public int IDE_VEN { get; set; }
        public string NOM_VEN { get; set; }
        public string APE_VEN { get; set; }
        public string DIR_VEN { get; set; }
        public string TEL_VEN { get; set; }
        public int IDE_DIS { get; set; }
        public string COR_VEN { get; set; }
        public decimal SUE_VEN { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
    }
}
